-- ============================================================
-- session_context — snapshot of what the AI knew at session start
-- Stored for audit/replay: "what context was loaded this session?"
-- Also stores conversation_summary for sessions with long transcripts.
-- ============================================================

alter table sessions
  add column if not exists session_context jsonb;

comment on column sessions.session_context is
  'Snapshot of the context assembled at session start.
   Populated by loadSessionContext() in useInterview / usePractice.
   Structure: {
     profile_snapshot: { display_name, experience_years, primary_role, ... },
     topic_mastery:    { topicName, masteryLevel, totalAttempts, avgScore },
     memories_loaded:  number,   -- how many user_memory rows were injected
     solutions_loaded: number,   -- how many user_solutions rows were injected
     context_assembled_at: ISO string
   }
   Used for debugging and session replay. Not read by the AI directly — the
   assembled prompt text is what the AI sees.';

-- ── conversation_summary column ───────────────────────────────────────────────
-- When a session transcript exceeds the rolling window, older messages are
-- summarized into a single string stored here. The summary is prepended to
-- the prompt as a [Earlier in this session: ...] block.

alter table sessions
  add column if not exists conversation_summary text;

comment on column sessions.conversation_summary is
  'Rolling summary of conversation messages that have been pushed out of the
   active 20-message window. Generated by trimConversation() in useInterview.ts.
   Prepended to the system prompt as: [Earlier in this session: {summary}]';
